/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogodavelha;

import java.awt.Color;
import javax.swing.UIManager;


/**
 *
 * @author Maria Fernanda
 */
public class JogoDaVelha extends javax.swing.JFrame {
    public boolean xis = true;
    public boolean bola = false;
    public int cont=0;
    public int lin0=0, lin1=0, lin2=0, col0=0, col1=0, col2=0, diag0=0, diag1=0;
    int[][] jogadas = new int [3][3];

    /**
     * Creates new form JogoDaVelha
     */
    public JogoDaVelha() {
        initComponents();
    }
    
    public void Rodada(javax.swing.JButton bt, int poslin, int poscol) {
        cont++; //conta as jogadas válidas, onde o máximo é 9
        if(xis){
            jogadas[poslin][poscol] = 2;
            bt.setText("X");
            cxtxtInfo.setText("Vez de O");
            this.xis = false;
            this.bola = true;
        } else if (bola) {
            jogadas[poslin][poscol] = 5;
            bt.setText("O");
            cxtxtInfo.setText("Vez de X");
            this.xis = true;
            this.bola = false;
        }
        bt.setEnabled(false);
    }
    
    public void SomaTudo(){
        lin0 = jogadas[0][0] + jogadas[0][1] + jogadas[0][2];
        lin1 = jogadas[1][0] + jogadas[1][1] + jogadas[1][2];
        lin2 = jogadas[2][0] + jogadas[2][1] + jogadas[2][2];
        
        col0 = jogadas[0][0] + jogadas[1][0] + jogadas[2][0];
        col1 = jogadas[0][1] + jogadas[1][1] + jogadas[2][1];
        col2 = jogadas[0][2] + jogadas[1][2] + jogadas[2][2];
        
        diag0 = jogadas[0][0] + jogadas[1][1] + jogadas[2][2];
        diag1 = jogadas[0][2] + jogadas[1][1] + jogadas[2][0];
    }
    
    public void ZeraSoma(){
        lin0=0;
        lin1=0;
        lin2=0;
        col0=0;
        col1=0;
        col2=0;
        diag0=0;
        diag1=0;
    }
    
    public void Verifica(){
        SomaTudo();
        if ((lin0 == 6) || (lin1 == 6) || (lin2 == 6) ||
                (col0 == 6) || (col1 == 6) || (col2 == 6)||
                (diag0 == 6) || (diag1 == 6)){
            Desabilita();
            cxtxtInfo.setForeground(Color.GREEN);
            cxtxtInfo.setText("X venceu ^_^" );
        } else if ((lin0 == 15) || (lin1 == 15) || (lin2 == 15) ||
                (col0 == 15) || (col1 == 15) || (col2 == 15)||
                (diag0 == 15) || (diag1 == 15)){
            Desabilita();
            cxtxtInfo.setForeground(Color.GREEN);
            cxtxtInfo.setText("O venceu ^_^" );
        } else if (cont == 9){
            Desabilita();
            cxtxtInfo.setForeground(Color.RED);
            cxtxtInfo.setText("Ninguém venceu T_T");
        }
        ZeraSoma();
    }
    public void ZeraVetor(){
        for (int i=0; i<3; i++){
            for (int j=0; j<3; j++){
                jogadas[i][j] = 0;
            }
        }
    }
    public void Restart() {        
        ZeraVetor();
        ZeraSoma();
        this.cont=0;
        this.xis = true;
        this.bola = false;
        bt00.setText("");
        bt00.setEnabled(true);
        bt01.setText("");
        bt01.setEnabled(true);
        bt02.setText("");
        bt02.setEnabled(true);
        bt10.setText("");
        bt10.setEnabled(true);
        bt11.setText("");
        bt11.setEnabled(true);
        bt12.setText("");
        bt12.setEnabled(true);
        bt20.setText("");
        bt20.setEnabled(true);
        bt21.setText("");
        bt21.setEnabled(true);
        bt22.setText("");
        bt22.setEnabled(true);
        cxtxtInfo.setForeground(Color.BLACK);
        cxtxtInfo.setText("Vez do Jogador X");  
    }
    
    public void Desabilita() {
        this.xis = false;
        this.bola = false;
        bt00.setEnabled(false);
        bt01.setEnabled(false);
        bt02.setEnabled(false);
        bt10.setEnabled(false);
        bt11.setEnabled(false);
        bt12.setEnabled(false);
        bt20.setEnabled(false);
        bt21.setEnabled(false);
        bt22.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt00 = new javax.swing.JButton();
        bt01 = new javax.swing.JButton();
        bt02 = new javax.swing.JButton();
        bt10 = new javax.swing.JButton();
        bt11 = new javax.swing.JButton();
        bt12 = new javax.swing.JButton();
        bt20 = new javax.swing.JButton();
        bt21 = new javax.swing.JButton();
        bt22 = new javax.swing.JButton();
        btRestart = new javax.swing.JButton();
        cxtxtInfo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt00.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 72)); // NOI18N
        bt00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt00ActionPerformed(evt);
            }
        });

        bt01.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 72)); // NOI18N
        bt01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt01ActionPerformed(evt);
            }
        });

        bt02.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 72)); // NOI18N
        bt02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt02ActionPerformed(evt);
            }
        });

        bt10.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 72)); // NOI18N
        bt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt10ActionPerformed(evt);
            }
        });

        bt11.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 72)); // NOI18N
        bt11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt11ActionPerformed(evt);
            }
        });

        bt12.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 72)); // NOI18N
        bt12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt12ActionPerformed(evt);
            }
        });

        bt20.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 72)); // NOI18N
        bt20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt20ActionPerformed(evt);
            }
        });

        bt21.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 72)); // NOI18N
        bt21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt21ActionPerformed(evt);
            }
        });

        bt22.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 72)); // NOI18N
        bt22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt22ActionPerformed(evt);
            }
        });

        btRestart.setFont(new java.awt.Font("Short Stack", 0, 18)); // NOI18N
        btRestart.setForeground(new java.awt.Color(0, 153, 255));
        btRestart.setText("reiniciar");
        btRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRestartActionPerformed(evt);
            }
        });

        cxtxtInfo.setEditable(false);
        cxtxtInfo.setFont(new java.awt.Font("Short Stack", 1, 18)); // NOI18N
        cxtxtInfo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cxtxtInfo.setText("Vez do Jogador X");
        cxtxtInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxtxtInfoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Jogo da Velha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxtxtInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bt20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bt21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bt22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bt10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bt11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bt12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bt00, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bt01, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bt02, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btRestart, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt00, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt01, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt02, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cxtxtInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btRestart, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btRestart.getAccessibleContext().setAccessibleDescription("Clique nesse botão para reiniciar a partida.");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt00ActionPerformed
        // TODO add your handling code here:
        Rodada(bt00,0,0);
        Verifica();
    }//GEN-LAST:event_bt00ActionPerformed

    private void bt01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt01ActionPerformed
        // TODO add your handling code here:
        Rodada(bt01,0,1);
        Verifica();
    }//GEN-LAST:event_bt01ActionPerformed

    private void bt02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt02ActionPerformed
        // TODO add your handling code here:
        Rodada(bt02,0,2);
        Verifica();
    }//GEN-LAST:event_bt02ActionPerformed

    private void bt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt10ActionPerformed
        // TODO add your handling code here:
        Rodada(bt10,1,0);
        Verifica();
    }//GEN-LAST:event_bt10ActionPerformed

    private void bt11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt11ActionPerformed
        // TODO add your handling code here:
        Rodada(bt11,1,1);
        Verifica();
    }//GEN-LAST:event_bt11ActionPerformed

    private void bt12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt12ActionPerformed
        // TODO add your handling code here:
        Rodada(bt12,1,2);
        Verifica();
    }//GEN-LAST:event_bt12ActionPerformed

    private void bt20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt20ActionPerformed
        // TODO add your handling code here:
        Rodada(bt20,2,0);
        Verifica();
    }//GEN-LAST:event_bt20ActionPerformed

    private void bt21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt21ActionPerformed
        // TODO add your handling code here:
        Rodada(bt21,2,1);
        Verifica();
    }//GEN-LAST:event_bt21ActionPerformed

    private void bt22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt22ActionPerformed
        // TODO add your handling code here:
        Rodada(bt22,2,2);
        Verifica();
    }//GEN-LAST:event_bt22ActionPerformed

    private void btRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRestartActionPerformed
        // TODO add your handling code here:
        Restart();
    }//GEN-LAST:event_btRestartActionPerformed

    private void cxtxtInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxtxtInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxtxtInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        UIManager.put("Button[Disabled].textForeground", Color.BLACK);        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoDaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoDaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoDaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoDaVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoDaVelha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt00;
    private javax.swing.JButton bt01;
    private javax.swing.JButton bt02;
    private javax.swing.JButton bt10;
    private javax.swing.JButton bt11;
    private javax.swing.JButton bt12;
    private javax.swing.JButton bt20;
    private javax.swing.JButton bt21;
    private javax.swing.JButton bt22;
    private javax.swing.JButton btRestart;
    private javax.swing.JTextField cxtxtInfo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}